language: node_js
node_js:
  - "node"

services:
  - postgresql

before_script:
  - psql -c 'create database stackreflow;' -U postgres

cache:
  directories:
    - node_modules

after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT