FORMAT: 1A
HOST: https://stackreflow.herokuapp.com/api/v1

# Stackreflow

Stackreflow is an API providing a platform like Stackoverflow(lite). 
Users can create account, login to ask questions and give answers to questions.
Users can also upvote or downvote an answer. 
And view profile to see summary of activities on the platform.

## Authentication - Signup [/auth/signup]

### Registers a user [POST]

You may register using this action. It takes a JSON
object containing a user details.

+ Request (application/json)

        {
            name: "KENZiE",
            email: "KenzDozz@gmail.com",
            password: "secret123",
        }

+ Response 200 (application/json)
    
        {
            status: true,
            user: [
                {
                    id: 1,
                    name: "KENZiE",
                    email: "KenzDozz@gmail.com",
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                },
            ]
        }

## Authentication - Login [/auth/login]

### Login a user [POST]

You may login using this action. It takes a JSON
object containing a user credentials and returns a JWT.

+ Request (application/json)

        {
            email: "KenzDozz@gmail.com",
            password: "secret123",
        }

+ Response 200 (application/json)
    
        {
            status: true,
            token: "uvtvcy73r8893y20fgf9vcyvcvg78gc7gbvy8g9vc9vc7g",
            user: [
                {
                    id: 1,
                    name: "KENZiE",
                    email: "KenzDozz@gmail.com",
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                },
            ]
        }

## Questions Collection [/questions]

### List All Questions [GET]

You may list all question using this action.
You may search for questions by pass a query 'search' string parameter.

+ Response 200 (application/json)
    
        {
            status: true,
            authCheck: false
            questions: [
                {
                    id: 1,
                    title: 'How can I write API documentation?',
                    body: 'How can I write proper documentation with API Blueprint',
                    tags: 'api, documentation',
                    user_id: 1,
                    username: 'KENZiE',
                    answered: false,
                    answer_count: 2,
                    view_count: 4,
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                    created: '2 hours ago',
                    manage: false,
                },
            ]
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON object containing a question.
Token REQUIRED.

+ Request (application/json)

        {
            title: "How to test a test code",
            body: "How can I test a test code, and can I test a chai code with jasmine?",
            tags: "test, code",
            token: "yuguyg37883899ufubbsdyg8fh9u0fbbeg87e980329rnfbu43984h4upb4984",
        }

+ Response 200 (application/json)

            {
                status: true,
                authCheck: true
                question: {
                        id: 2,
                        title: "How to test a test code",
                        body: "How can I test a test code, and can I test a chai code with jasmine?",
                        tags: "test, code",
                        user_id: 1,
                        username: "KENZiE",
                        answered: false,
                        answer_count: 2,
                        view_count: 4,
                        created_at: "2018-09-01T12:37:05.510Z",
                        updated_at: "2018-09-01T12:37:05.510Z",
                        created: "1 second ago",
                        manage: false,
                    }
            }

## Question Collection [/questions/{questionId}]

### Get a Question [GET]

You can get a question by passing the questionId parameter while calling this action.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer

+ Response 200 (application/json)

        {
            status: true,
            authCheck: true,
            question: {
                    id: 2,
                    title: "How to test a test code",
                    body: "How can I test a test code, and can I test a chai code with jasmine?",
                    tags: "test, code",
                    user_id: 1,
                    username: "KENZiE",
                    answered: false,
                    answer_count: 2,
                    view_count: 4,
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                    created: "1 second ago",
                    manage: false,
                },
            answers: [
                {
                    id: 1,
                    question_id: 2,
                    body: "A test code is meant to test a code and cannot be tested",
                    user_id: 2,
                    username: "Kenneth",
                    vote_count: 4,
                    accepted: false
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                },
            ]
        }

### Delete a Question [DELETE]

You can delete a question if you are the author by passing the questionId parameter while calling this action.
Token REQUIRED.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer

+ Response 200 (application/json)

        {
            status: true,
            authCheck: true
            question: {}
        }

## Answers Collection I [/questions/{questionId}/answers]

### Post an answer [POST]

You can post an answer to a question by passing the questionId parameter while calling this action.
Token REQUIRED.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer

+ Request (application/json)

        {
            body: "How can I test a test code, and can I test a chai code with jasmine?",
            token: "yuguyg37883899ufubbsdyg8fh9u0fbbeg87e980329rnfbu43984h4upb4984",
        }

+ Response 200 (application/json)

        {
            status: true,
            authCheck: true,
            answer: {
                    id: 1,
                    question_id: 2,
                    body: "A test code is meant to test a code and cannot be tested",
                    user_id: 2,
                    username: "Kenneth",
                    vote_count: 4,
                    accepted: false
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                },
        }

## Answers Collection II [/questions/{questionId}/answers/{answerId}]

### Accept an answer [PUT]

You can accept an answer to a question if you are the author of the question by passing the questionId and answerId parameters while calling this action.
Token REQUIRED.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer
    + answerId (number) - ID of the Answe in the form of an integer

+ Response 200 (application/json)

        {
            status: true,
            authCheck: true,
            message: "Answer accepted",
        }

### Delete an Answer [DELETE]

You can delete an answer if you are the author by passing the questionId and answerId parameters while calling this action.
Token REQUIRED.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer
    + answerId (number) - ID of the Answe in the form of an integer

+ Response 200 (application/json)

        {
            status: true,
            authCheck: true
            answer: {}
        }

## Vote - upvote [/questions/{questionId}/answers/{answerId}/upvote]

### Upvote an answer [PUT]

You can upvote an answer to a question by passing the questionId and answerId parameters while calling this action.
Token REQUIRED.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer
    + answerId (number) - ID of the Answe in the form of an integer

+ Response 200 (application/json)

            status: true,
            vote: {
                id: 1,
                user_id: 2,
                answer_id: 1,
                vote: 1,
                created_at: "2018-09-01T12:37:05.510Z",
                updated_at: "2018-09-01T12:37:05.510Z",
            },

## Vote - downvote [/questions/{questionId}/answers/{answerId}/downvote]

### Downvote an answer [PUT]

You can downvote an answer to a question by passing the questionId and answerId parameters while calling this action.
Token REQUIRED.

+ Parameters

    + questionId (number) - ID of the Question in the form of an integer
    + answerId (number) - ID of the Answe in the form of an integer

+ Response 200 (application/json)

        {
            status: true,
            vote: {
                id: 1,
                user_id: 2,
                answer_id: 1,
                vote: -1,
                created_at: "2018-09-01T12:37:05.510Z",
                updated_at: "2018-09-01T12:37:05.510Z",
            },
        }


## Users collection [/users]

### Get all users [GET]

You can get all registered users by calling this action.

+ Response 200 (application/json)

        {
            status: true,
            users: [
                {
                    id: 1,
                    name: 'KENZiE',
                    email: 'KenzDozz@gmail.com',
                    question_count: 7,
                    answer_count: 22,
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                },
        }

## User collection [/users/{userId}]

### Get a user [GET]

You can get a particular registered user and questions asked by calling this action while passing the user ID.
You may pass a query string 'top' to sort questions by most responded to, or pass query string 'answers' to retrieve questions the user has given answer to.

+ Parameters

    + userId (number) - ID of the user in the form of an integer

+ Response 200 (application/json)

        {
            status: true,
            user: {
                        id: 1,
                        name: 'KENZiE',
                        email: 'KenzDozz@gmail.com',
                        question_count: 7,
                        answer_count: 22,
                        created_at: "2018-09-01T12:37:05.510Z",
                        updated_at: "2018-09-01T12:37:05.510Z",
                    },
            questions: [
                {
                    id: 1,
                    title: 'How can I write API documentation?',
                    body: 'How can I write proper documentation with API Blueprint',
                    tags: 'api, documentation',
                    user_id: 1,
                    username: 'KENZiE',
                    answered: false,
                    answer_count: 2,
                    view_count: 4,
                    created_at: "2018-09-01T12:37:05.510Z",
                    updated_at: "2018-09-01T12:37:05.510Z",
                    created: '2 hours ago',
                    manage: false,
                },
            ]
        }

